### ISSUE TITLE
go run main.go error

### ISSUE THREAD

**Issue by vonhenry** [textileio/lotus-devnet#28]
$  go run main.go
2020-08-28T15:20:05.001+0800    INFO    devnet-main     lotus-devnet/main.go:42 Starting devnet with speed = 100, numminers = 1, bigsectors = true, ipfsaddr = 
2020-08-28T15:20:05.005+0800    WARN    chainstore      store/store.go:136      no previous chain state found
2020-08-28T15:20:05.005+0800    WARN    genesis testing/genesis.go:36   Generating new random genesis block, note that this SHOULD NOT happen unless you are setting up new network
init set t3rmhisoreec55bj5ahg47fzexdqs2vdg7jaa3yl2b4wjaycc5kbsr7hauns3fw7nyatnuypurmwahden5oo4q t0100
publishing 2 storage deals on miner t01000 with worker t3rmhisoreec55bj5ahg47fzexdqs2vdg7jaa3yl2b4wjaycc5kbsr7hauns3fw7nyatnuypurmwahden5oo4q
Added weight to claim:  536870912 5368709121
Added weight to claim:  1073741824 10737418241
2020-08-28T15:20:05.007+0800    INFO    genesis genesis/genesis.go:331  Empty Genesis root: bafy2bzaceaa43et73tgxsoh2xizd4mxhbrcfig4kqp25zfa5scdgkzppllyuu
2020-08-28T15:20:05.007+0800    WARN    chainstore      store/store.go:347      no heaviest tipset found, using [bafy2bzacedqom6thsriedpjf7uhvgpa46bhgi4pti5zqysuvnglsqrrunz4c4]
2020-08-28T15:20:05.007+0800    INFO    chainstore      store/store.go:352      New heaviest tipset! [bafy2bzacedqom6thsriedpjf7uhvgpa46bhgi4pti5zqysuvnglsqrrunz4c4] (height=0)
2020-08-28T15:20:05.007+0800    INFO    p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/0.0.0.0/tcp/0 /ip6/::/tcp/0]
2020-08-28T15:20:05.007+0800    INFO    dht/RtRefreshManager    rtrefresh/rt_refresh_manager.go:265     starting refreshing cpl 0 with key  b� (routing table size was 0)
2020-08-28T15:20:05.007+0800    WARN    dht/RtRefreshManager    rtrefresh/rt_refresh_manager.go:128     failed when refreshing routing table2 errors occurred:
        * failed to query for self, err=failed to run refresh DHT query for key= vqL�<�U�*�ヹ;�kUK��=&� �|�p, err=failed to find any peer in table
        * failed to refresh cpl=0, err=failed to run refresh DHT query for key= b�, err=failed to find any peer in table

panic: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleIncomingBlocks (/Users/song/Code/Golang/pkg/mod/github.com/filecoin-project/lotus@v0.4.0/node/modules/services.go:61): failed to build *pubsub.PubSub: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.DrandBootstrap: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: lookup _dnsaddr.pl-eu.testnet.drand.sh on 10.0.254.113:53: no such host

goroutine 1 [running]:
main.main()
        /Users/song/Code/Golang/src/github.com/textileio/lotus-devnet/main.go:46 +0x5e0
exit status 2

OS:macos calitina    version 10.15.6

**Comment by jsign** [comment]
Thanks for creating the issue, since this is a well-known problem in Lotus (not really this repo, but surfaces).
This looks like was fixed in Lotus [20 hours ago](https://github.com/filecoin-project/lotus/issues/3335), so it might take some time to fully permeate in here since that fix should be merged in some next deployment.

In the meantime, they only proposed solution is retrying since in theory should be sporadic... but I've heard some people like you that had to wait sometime. Maybe the DRAND node is trying to connect depends on location.

**Comment by vonhenry** [comment]
> Thanks for creating the issue, since this is a well-known problem in Lotus (not really this repo, but surfaces).
> This looks like was fixed in Lotus [20 hours ago](https://github.com/filecoin-project/lotus/issues/3335), so it might take some time to fully permeate in here since that fix should be merged in some next deployment.
> 
> In the meantime, they only proposed solution is retrying since in theory should be sporadic... but I've heard some people like you that had to wait sometime. Maybe the DRAND node is trying to connect depends on location.

thanks so much, it works now!
